/**
 * @file Payload.gs
 * Webhook payload builders. One builder per webhook contract.
 *
 * Builders own the wire format (snake_case) and the field-name contract.
 * Callers pass JS-idiomatic camelCase args; builders translate.
 *
 * payload_version is NOT stamped here â€” Webhook.call owns that invariant.
 *
 * Public:
 *   Payload.provision(args)    â†’ object
 *   Payload.validate(args)     â†’ object
 *   Payload.portalInvite(args) â†’ object
 *
 * Each builder validates its required args and throws on missing/blank.
 * Optional fields are normalized.
 */

var Payload = {};

// --- Provision -------------------------------------------------------

/**
 * Build the provision webhook payload (R-1 Receive Webhook contract).
 *
 * Wire-format changes in payload_version 2.0:
 *   - config_json_file_id renamed to drive_id_config_json
 *   - is_initial added (boolean; menu-derived: "Start supplier data
 *     collection" â†’ true, "Update configuration" â†’ false)
 *
 * Wire-format changes in payload_version 3.0:
 *   - output_drive_folder_id added (string; from 1_customer).
 *     Distinct from config_file_id (the workbook) and from
 *     storage.configExportFolderId (where the library writes config JSON).
 *     This is Workato's output destination.
 *   - reminder_days_1, reminder_days_2, reminder_days_3 added (integers;
 *     from 1_customer). Cadence for non-compliant supplier reminders.
 *
 * @param {Object} args
 * @param {string}  args.correlationId        - UUID linking the request across systems.
 * @param {string}  args.clientName           - From 1_customer.
 * @param {string}  args.analystEmail         - From 1_customer.
 * @param {string}  args.configFileId         - The workbook's own Drive file ID (ss.getId()).
 * @param {string}  args.configJsonFileId     - The serialized JSON's Drive file ID.
 *                                              Wire field: drive_id_config_json.
 * @param {boolean} args.isInitial            - True for initial provision runs;
 *                                              false for update runs. Menu-derived.
 * @param {string}  args.outputDriveFolderId  - From 1_customer. Drive folder
 *                                              where Workato writes outputs.
 * @param {number}  args.reminderDays1        - From 1_customer. Days to first reminder.
 * @param {number}  args.reminderDays2        - From 1_customer. Days to second reminder.
 * @param {number}  args.reminderDays3        - From 1_customer. Days to third reminder.
 * @param {string}  [args.targetVms='']       - Optional, from 1_customer.
 * @param {boolean} [args.separateWorkspace=false] - From 1_customer.
 * @param {Array}   [args.templateFileIds=[]] - Drive file IDs of per-variant
 *   config JSONs, in variant_index order. Empty when 1_customer!D6 = 0.
 *   Generated by Variant.serializeAll before this builder is called.
 * @returns {Object} wire-format payload
 */
Payload.provision = function(args) {
  Payload._requireArgs(args,
    ['correlationId', 'clientName', 'analystEmail',
     'configFileId', 'configJsonFileId', 'isInitial',
     'outputDriveFolderId', 'reminderDays1', 'reminderDays2', 'reminderDays3'],
    'provision');

  return {
    correlation_id:              args.correlationId,
    client_name:                 args.clientName,
    analyst_email:               args.analystEmail,
    target_vms:                  args.targetVms || '',
    config_file_id:              args.configFileId,
    drive_id_config_json:        args.configJsonFileId,
    template_file_ids:           args.templateFileIds || [],
    separate_workspace_required: Boolean(args.separateWorkspace),
    is_initial:                  Boolean(args.isInitial),
    output_drive_folder_id:      args.outputDriveFolderId,
    reminder_days_1:             args.reminderDays1,
    reminder_days_2:             args.reminderDays2,
    reminder_days_3:             args.reminderDays3,
    timestamp:                   new Date().toISOString()
  };
};

// --- Validate --------------------------------------------------------

/**
 * Build the validate webhook payload.
 */
Payload.validate = function(args) {
  Payload._requireArgs(args, ['correlationId', 'configJsonFileId', 'requesterEmail'],
                       'validate');

  return {
    correlation_id:      args.correlationId,
    config_json_file_id: args.configJsonFileId,
    requester_email:     args.requesterEmail,
    timestamp:           new Date().toISOString()
  };
};

// --- Portal invite ---------------------------------------------------

/**
 * Build the portal invite webhook payload.
 */
Payload.portalInvite = function(args) {
  Payload._requireArgs(args, ['correlationId', 'userEmail', 'role'], 'portalInvite');

  return {
    correlation_id: args.correlationId,
    user_email:     args.userEmail,
    contact_name:   args.contactName || '',
    role:           args.role,
    timestamp:      new Date().toISOString()
  };
};

// --- Private ---------------------------------------------------------

/**
 * Validate that args is present and all named fields are non-empty.
 *
 * Treats boolean false as a valid value â€” it must, because is_initial
 * legitimately carries `false` for update runs. The check is "field is
 * present and not null/undefined/blank-string," NOT "field is truthy."
 */
Payload._requireArgs = function(args, required, builderName) {
  if (!args) {
    throw new Error('Payload.' + builderName + ': args object is required.');
  }
  for (var i = 0; i < required.length; i++) {
    var k = required[i];
    var v = args[k];
    if (v === null || v === undefined || (typeof v === 'string' && v.trim() === '')) {
      throw new Error('Payload.' + builderName + ': "' + k + '" is required and must be non-empty.');
    }
  }
};
